/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bernalpablojava03;

import java.util.GregorianCalendar;
import javax.swing.JOptionPane;



/**
 *
 * @author bersa
 */
public class NewJFrame extends javax.swing.JFrame {

    Lista lista = new Lista();
    Boolean enCreacion = false;
    Boolean enModificacion = false;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoNumeroCuenta = new javax.swing.JTextField();
        textoPropietario = new javax.swing.JTextField();
        textoSaldo = new javax.swing.JTextField();
        textoFecha = new javax.swing.JTextField();
        botonBorrar = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        botonAnterior = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar cuentas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 200));
        setName("Control de cuentas"); // NOI18N

        jLabel1.setText("Numero de cuenta:");

        jLabel2.setText("Propietario:");

        jLabel3.setText("Fecha de creacion:");

        jLabel4.setText("Saldo:");

        textoNumeroCuenta.setFocusable(false);
        textoNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNumeroCuentaActionPerformed(evt);
            }
        });

        textoPropietario.setFocusable(false);
        textoPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPropietarioActionPerformed(evt);
            }
        });

        textoSaldo.setFocusable(false);

        textoFecha.setFocusable(false);

        botonBorrar.setText("Borrar");
        botonBorrar.setEnabled(false);
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrar(evt);
            }
        });

        botonSiguiente.setText("Siguiente");
        botonSiguiente.setEnabled(false);
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguiente(evt);
            }
        });

        botonAnterior.setText("Anterior");
        botonAnterior.setEnabled(false);
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnterior(evt);
            }
        });

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrear(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.setEnabled(false);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAnterior)
                            .addComponent(botonCrear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSiguiente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonBorrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnterior)
                    .addComponent(botonSiguiente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrear)
                    .addComponent(botonModificar)
                    .addComponent(botonBorrar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNumeroCuentaActionPerformed

    private void textoPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPropietarioActionPerformed

    private void actualizarDatos(){
        focusTexto(false);
        if(lista.getNodo() == null){
            vaciarDatos();
            botonCrear.setEnabled(true);
            botonModificar.setEnabled(false);
            botonBorrar.setEnabled(false);
            botonAnterior.setEnabled(false);
            botonSiguiente.setEnabled(false);
        }
        else{
            Cuenta cuenta = (Cuenta)lista.getNodo().getContenido();
            //Campos de texto
            textoNumeroCuenta.setText(Integer.toString(cuenta.getNumeroCuenta()));
            textoPropietario.setText(cuenta.getPropietario());
            textoFecha.setText(cuenta.gregorianTexto());
            Cuenta aux = (Cuenta)lista.getNodo().getContenido();
            if(aux.getSaldo()*100%10 != 0){
                textoSaldo.setText(""+aux.getSaldo()+" €");
            }
            else{
                textoSaldo.setText(""+aux.getSaldo()+"0 €");
        }
            //Botones
            if(lista.getNodo().getAnterior() == null){botonAnterior.setEnabled(false);}
            else{botonAnterior.setEnabled(true);}
            if(lista.getNodo().getSiguiente() == null){botonSiguiente.setEnabled(false);}
            else{botonSiguiente.setEnabled(true);}
            botonCrear.setEnabled(true);
            botonBorrar.setEnabled(true);
            botonModificar.setEnabled(true);
        }
        
    }
    
    private void vaciarDatos(){
        textoNumeroCuenta.setText("");
        textoPropietario.setText("");
        textoFecha.setText("");
        textoSaldo.setText("");
    }
    
    private GregorianCalendar recogerFecha(String fecha) throws NumberFormatException {
        String fechaSeparada[] = fecha.split("/", 3);
        int day = Integer.parseInt(fechaSeparada[0]);
        int month = Integer.parseInt(fechaSeparada[1]);
        int year = Integer.parseInt(fechaSeparada[2]);
        return new GregorianCalendar(year, month, day);
    }
    
    private boolean fechaFormatoCorrecto(String fecha){
        if("".equals(fecha)){
            return true;
        }
        //Comprobacion de formato
        if(!fecha.matches("\\d+/\\d+/\\d+")){
            return false;
        }
        //Comprobacion de numeros
        String fechaSeparada[] = fecha.split("/", 3);
        int day = Integer.parseInt(fechaSeparada[0]);
        int month = Integer.parseInt(fechaSeparada[1]);
        //Minimos y maximos estandar
        if(month < 1 || month > 12 || day < 1 || day > 31){
            return false;
        }
        //Febrero
        if(month == 2 && day > 29){
            return false;
        }
        //Meses de 30 dias
        return !(month < 7 && month%2 == 0 && day > 30 || month > 7 && month%2 != 0 && day > 30);
    }
    private boolean saldoFormatoCorrecto(String saldo){
        return saldo.matches("\\d+.\\d+") || saldo.matches("\\d+") || "".equals(saldo);
    }
    
    private boolean numeroCuentaFormatoCorrecto(String numeroCuenta){
        return numeroCuenta.matches("\\d+") || "".equals(numeroCuenta);
    }
    
    private void focusTexto(Boolean truefalse){
            textoNumeroCuenta.setFocusable(truefalse);
            textoPropietario.setFocusable(truefalse);
            textoFecha.setFocusable(truefalse);
            textoSaldo.setFocusable(truefalse);
    }
    
    private boolean datosCorrectos(){
        if(!numeroCuentaFormatoCorrecto(textoNumeroCuenta.getText())){
            JOptionPane.showMessageDialog(null, "Se ha introducido algo distinto a un numero en el numero de cuenta." + 
                                                "\nEjemplo: 12" + 
                                                "\nIntroducido: " + textoNumeroCuenta.getText(),"ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!fechaFormatoCorrecto(textoFecha.getText())){
            JOptionPane.showMessageDialog(null, "Se ha introducido una fecha con formato incorrecto." + 
                                                "\nEjemplo: dd/mm/yyyy" + 
                                                "\nIntroducido: " + textoFecha.getText(),"ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!saldoFormatoCorrecto(textoSaldo.getText())){
            JOptionPane.showMessageDialog(null, "Se ha introducido el saldo con formato incorrecto." + 
                                                "\nEjemplo: 1000" + 
                                                "\nEjemplo: 1000.25" + 
                                                "\nIntroducido: " + textoSaldo.getText(),"ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void cuentaNueva(){
        //Campos vacios
        if("".equals(textoNumeroCuenta.getText()) && "".equals(textoPropietario.getText()) && "".equals(textoFecha.getText()) && "".equals(textoSaldo.getText())){
            lista.nuevoNodo(new Nodo(new Cuenta()));
            return;
        }
        //Formato para el saldo
        String saldoAux = textoSaldo.getText().replace(",", ".");
        
        //Fecha vacia
        if("".equals(textoFecha.getText())){
            lista.nuevoNodo(new Nodo(new Cuenta(textoNumeroCuenta.getText(),
                                                textoPropietario.getText(),
                                                saldoAux)));
        }
        //Fecha llena
        else{
            lista.nuevoNodo(new Nodo(new Cuenta(textoNumeroCuenta.getText(),
                                                textoPropietario.getText(),
                                                recogerFecha(textoFecha.getText()),
                                                saldoAux)));
        }
        
    }
    
    private void botonAnterior(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnterior
        if(!enCreacion && !enModificacion){
            lista.anterior();
            botonSiguiente.setEnabled(true);
        }
        else{
            botonAnterior.setText("Anterior");
            botonSiguiente.setText("Siguiente");
            enCreacion = false;
            enModificacion = false;
        }
        actualizarDatos();
    }//GEN-LAST:event_botonAnterior

    private void botonSiguiente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguiente
        if(!enCreacion && !enModificacion){
            lista.siguiente();
            botonAnterior.setEnabled(true);
            actualizarDatos();
        }
        else{
            if(enCreacion){
                if(datosCorrectos()){
                    enCreacion = false;
                    cuentaNueva();
                    botonAnterior.setText("Anterior");
                    botonSiguiente.setText("Siguiente");
                    actualizarDatos();
                }
            }
            if(enModificacion && datosCorrectos()){
                enModificacion = false;
                botonAnterior.setText("Anterior");
                botonSiguiente.setText("Siguiente");
                actualizarDatos();
                lista.modificarCuenta(textoNumeroCuenta.getText(),
                                          textoPropietario.getText(),
                                          textoFecha.getText(),
                                          textoSaldo.getText());                
            }
        }
        
    }//GEN-LAST:event_botonSiguiente

    private void botonCrear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrear
        if(!enCreacion){
            enCreacion = true;
            textoNumeroCuenta.setText("");
            textoPropietario.setText("");
            textoFecha.setText("");
            textoSaldo.setText("");
            botonCrear.setEnabled(false);
            botonModificar.setEnabled(false);
            botonBorrar.setEnabled(false);
            botonAnterior.setEnabled(true);
            botonAnterior.setText("Cancelar");
            botonSiguiente.setEnabled(true);
            botonSiguiente.setText("Aceptar");
            focusTexto(true);
        }
        else{
            
        }
    }//GEN-LAST:event_botonCrear

    private void botonModificar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificar
        focusTexto(true);
        enModificacion = true;
        //Botones
        botonCrear.setEnabled(false);
        botonModificar.setEnabled(false);
        botonBorrar.setEnabled(false);
        botonAnterior.setEnabled(true);
        botonAnterior.setText("Cancelar");
        botonSiguiente.setEnabled(true);
        botonSiguiente.setText("Aceptar");
        //Formato
        textoSaldo.setText(textoSaldo.getText().replace(" €", ""));
    }//GEN-LAST:event_botonModificar

    private void botonBorrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrar
        lista.borrarNodo();
        actualizarDatos();
    }//GEN-LAST:event_botonBorrar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textoFecha;
    private javax.swing.JTextField textoNumeroCuenta;
    private javax.swing.JTextField textoPropietario;
    private javax.swing.JTextField textoSaldo;
    // End of variables declaration//GEN-END:variables
}
